### ISSUE TITLE
Relative fontPath

### ISSUE THREAD

**Issue by fhoner** [Mika-/grunt-google-fonts#9]
Using a relative fontPath like **'../fonts/'** is not working and a empty fontPath will be used instead.
The css files in my project are minified into a single file, and the font path has to be set to a relative path in order to find the fonts folder. Also fonts wont get downloaded at all.

```javascript
googlefonts: {
            build: {
                options: {
                    fontPath: '../fonts/',
                    cssFile: 'dist/css/fonts.css',
                    fonts: [
                        {
                            family: 'Open Sans',
                            styles: [
                                400, 700
                            ]
                        }
                    ]
                }
            }
        }
```

generates

```css
@font-face {
	font-family: 'Open Sans';
	font-style: normal;
	font-weight: 400;
	src: local('Open Sans'), local('OpenSans'), url(/open-sans-400-normal.woff2) format('woff'), url(/open-sans-400-normal.woff) format('woff');
}
@font-face {
	font-family: 'Open Sans';
	font-style: normal;
	font-weight: 700;
	src: local('Open Sans Bold'), local('OpenSans-Bold'), url(/open-sans-700-normal.woff2) format('woff'), url(/open-sans-700-normal.woff) format('woff');
}
```
